--CREATE DATABASE "d288f6eqo19ebf"
--    WITH
--    OWNER = postgres
--    ENCODING = 'UTF8'
--    LC_COLLATE = 'Russian_Russia.1251'
--    LC_CTYPE = 'Russian_Russia.1251'
--    TABLESPACE = pg_default
--    CONNECTION LIMIT = -1;

-- Table: public."user"

-- DROP TABLE public."user";

CREATE TABLE public."user"
(
    "userName" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    password character varying(150) COLLATE pg_catalog."default" NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    active boolean,
    CONSTRAINT id PRIMARY KEY (id),
    CONSTRAINT "userName_unique" UNIQUE ("userName")
)

TABLESPACE pg_default;

ALTER TABLE public."user"
    OWNER to postgres;

--=========================================================================

-- Table: public.role

-- DROP TABLE public.role;

CREATE TABLE public.role
(
    "roleName" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    description character varying(150) COLLATE pg_catalog."default",
    CONSTRAINT role_pkey PRIMARY KEY ("roleName")
)

TABLESPACE pg_default;

ALTER TABLE public.role
    OWNER to postgres;

--==========================================================================

-- Table: public."userRoleRef"

-- DROP TABLE public."userRoleRef";

CREATE TABLE public."userRoleRef"
(
    "roleName" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "userName" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT role_fk FOREIGN KEY ("roleName")
        REFERENCES public.role ("roleName") MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "userName_fk" FOREIGN KEY ("userName")
        REFERENCES public."user" ("userName") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."userRoleRef"
    OWNER to postgres;

--========================================================================

-- Table: public.currency

-- DROP TABLE public.currency;

CREATE TABLE public.currency
(
    "CurrencyCode" character varying(3) COLLATE pg_catalog."default" NOT NULL,
    "Description" character varying(100) COLLATE pg_catalog."default",
    "NumCode" character(3) COLLATE pg_catalog."default",
    "Nominal" bigint,
    CONSTRAINT "currency_PK" PRIMARY KEY ("CurrencyCode")
)

TABLESPACE pg_default;

ALTER TABLE public.currency
    OWNER to postgres;

--===========================================================================

-- Table: public."exchRates"

-- DROP TABLE public."exchRates";

CREATE TABLE public."exchRates"
(
    "DateRate" date NOT NULL,
    "CurrencyCode" character varying(3) COLLATE pg_catalog."default" NOT NULL,
    "CurrencyRate" double precision NOT NULL,
    CONSTRAINT "exchRates_pkey" PRIMARY KEY ("DateRate", "CurrencyCode"),
    CONSTRAINT "CurrencyCode_FK" FOREIGN KEY ("CurrencyCode")
        REFERENCES public.currency ("CurrencyCode") MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."exchRates"
    OWNER to postgres;

-- Index: dateExchRate_Idx

-- DROP INDEX public."dateExchRate_Idx";

CREATE INDEX "dateExchRate_Idx"
    ON public."exchRates" USING btree
    ("DateRate" ASC NULLS LAST)
    TABLESPACE pg_default;

--=====================================================================

-- Table: public."historyQuery"

-- DROP TABLE public."historyQuery";

CREATE TABLE public."historyQuery"
(
    "currencyCodeFrom" character varying(3) COLLATE pg_catalog."default" NOT NULL,
    "currencyCodeTo" character varying(3) COLLATE pg_catalog."default" NOT NULL,
    "convertVal" double precision,
    "resultVal" double precision,
    "dateConvert" date,
    CONSTRAINT "currencyFrom_FK" FOREIGN KEY ("currencyCodeFrom")
        REFERENCES public.currency ("CurrencyCode") MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
        NOT VALID,
    CONSTRAINT "currencyTo_FK" FOREIGN KEY ("currencyCodeTo")
        REFERENCES public.currency ("CurrencyCode") MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."historyQuery"
    OWNER to postgres;

-- Index: date_Idx

-- DROP INDEX public."date_Idx";

CREATE INDEX "date_Idx"
    ON public."historyQuery" USING btree
    ("dateConvert" ASC NULLS LAST)
    TABLESPACE pg_default;

